### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fabaff** [kmike/text-unidecode#9]
As the "Artistic License" is not considered free by the FSF, it makes it impossible to include it in distribution which care about the licensing. It's also a blocker for packages which are relaying on text-unidecode.

Would you please consider to do a relicening to "Artistic clarified" or "Artistic 2.0"? Thanks.

Related issue: https://bugzilla.redhat.com/show_bug.cgi?id=1726400

**Comment by dmsimard** [comment]
This issue is also discussed in python-faker where text-unidecode is used as a dependency: https://github.com/joke2k/faker/issues/727

Would really appreciate if @kmike could weigh in as to whether changing the license is an option or not.

**Comment by kmike** [comment]
I'm using Artistic License to have the same license as https://metacpan.org/pod/release/SBURKE/Text-Unidecode-0.04/lib/Text/Unidecode.pm#COPYRIGHT-AND-DISCLAIMERS, which this package is based on. It says "the same license as Perl"; Perl is actually [dual GPL and Artistic](https://dev.perl.org/licenses/), not just Artistic.

I'm not sure it is good to choose anything else, to respect the original package.

Will having text-unidecode double-licensed (GPL + Artistic) solve the problem? If so, pull requests are welcome.

**Comment by dmsimard** [comment]
@kmike thanks for getting back to us and for the additional context !

The perl text-unidecode library is packaged appropriately as GPL+ or Artistic:
https://src.fedoraproject.org/rpms/perl-Text-Unidecode/blob/master/f/perl-Text-Unidecode.spec
```
[...]
Name:     perl-Text-Unidecode
Version:  1.30
Release:  9%{?dist}
Summary:  US-ASCII transliterations of Unicode text
License:  GPL+ or Artistic
URL:      https://metacpan.org/release/Text-Unidecode
Source0:  https://cpan.metacpan.org/modules/by-module/Text/Text-Unidecode-%{version}.tar.gz
[...]
```

I am not a lawyer but but going off by that example and considering the licensing of Perl itself, I believe it would resolve this issue if this python implementation of text-unicode would be licensed under the same terms.

**Comment by dmsimard** [comment]
@kmike I'm not very comfortable sending a PR to adjust the license of a project I have not authored or have contributed to -- it doesn't feel appropriate ? Would you mind doing it ?

**Comment by fabaff** [comment]
It would be nice if this could be resolved anytime soon.

**Comment by kmike** [comment]
Thanks for raising this; I've updated the license information and made 1.3 release.

**Comment by fabaff** [comment]
Thanks for your support.

**Comment by fcurella** [comment]
Hi, 

The Artistic License v1.0 is [forbidden by the Fedora Project](https://fedoraproject.org/wiki/Licensing:Main#Bad_Licenses), and it's causing us [packaging issues ](https://github.com/joke2k/faker/pull/990) upstream with python-faker.

Would it possible the use [Artistic _Clarified_](https://fedoraproject.org/wiki/Licensing/ArtisticClarified) license, or the [Artistic 2.0](http://www.perlfoundation.org/artistic_license_2_0) instead?

**Comment by kmike** [comment]
Hey! I don't think I can change the license, as it is inherited from the Perl module. But it shouldn't be a problem, as dual Artistic+GPL is in "Good" license list for Fedora.

**Comment by jimleroyer** [comment]
We wanted to use Faker in our open [source GCNotify project](https://github.com/cds-snc/notification-api) and as it relies on this dependency, Snyk reported a licensing incompatibility with MIT. Unfortunately, it seems that Artistic License version 1 is not compatible with our MIT license. 

I'm not here to complain, quite the contrary. I just wish we could use this library, reporting one more use case where we wish it would be possible to have the recommended clarified or v2 library. Thanks for your effort with this library!
